version: "3.9"

services:
  db:
    image: postgis/postgis:14-3.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    container_name: server
    depends_on:
      - db
    volumes:
      - ./services/server/:/app
    ports:
      - "5000:80"

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    container_name: web
    depends_on:
      - server
    volumes:
      - ./services/web/:/usr/app
      - node_modules_web:/usr/app/node_modules
    ports:
      - "3000:3000"

volumes:
  dbdata:
  node_modules_web:
